#!/usr/bin/env python3
"""Render a GitHub CODEOWNERS file from declared role contracts and explicit identities."""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

import yaml

IDENTITY = re.compile(r'^@[A-Za-z0-9_.-]+(?:/[A-Za-z0-9_.-]+)?$')


def load_yaml(path: Path) -> dict[str, Any]:
    payload = yaml.safe_load(path.read_text(encoding='utf-8'))
    if not isinstance(payload, dict):
        raise ValueError(f'{path}: expected an object')
    return payload


def render(contract: dict[str, Any], identities: dict[str, Any]) -> str:
    roles = identities.get('roles')
    if not isinstance(roles, dict):
        raise ValueError('identity map requires roles object')
    items = contract.get('contracts', [])
    if not isinstance(items, list):
        raise ValueError('sync contract requires contracts list')
    reviewer_identities: list[str] = []
    for item in items:
        if not isinstance(item, dict):
            raise ValueError('sync contract contains non-object contract')
        reviewer = item.get('reviewer')
        identity = roles.get(reviewer)
        if not isinstance(identity, str) or not IDENTITY.fullmatch(identity):
            raise ValueError(f'{reviewer!r}: requires an explicit GitHub @user or @org/team identity')
        reviewer_identities.append(identity)
    common_identities = ' '.join(sorted(set(reviewer_identities)))
    protected = ['governance/**', 'docs/**', 'roles/**', 'handoffs/**', 'profiles/templates/*.SOUL.md', 'templates/**', 'skills/**']
    lines = ['# Generated by scripts/render_codeowners.py; do not edit by hand.', '']
    lines.extend(f'/{pattern} {common_identities}' for pattern in protected)
    seen: set[str] = set(protected)
    for item in items:
        reviewer = item['reviewer']
        identity = roles[reviewer]
        sources = item.get('sources', [])
        dependents = item.get('dependents', [])
        if not isinstance(sources, list) or not isinstance(dependents, list):
            raise ValueError(f"{item.get('id', '<unknown>')}: sources and dependents must be lists")
        for pattern in [*sources, *dependents]:
            if not isinstance(pattern, str) or not pattern or pattern in seen:
                continue
            seen.add(pattern)
            lines.append(f'/{pattern} {identity}')
    return '\n'.join(lines) + '\n'


def main() -> int:
    parser = argparse.ArgumentParser()
    root = Path(__file__).resolve().parents[1]
    parser.add_argument('--contract', type=Path, default=root / 'governance/sync-contract.yaml')
    parser.add_argument('--identities', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    try:
        content = render(load_yaml(args.contract), load_yaml(args.identities))
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(content, encoding='utf-8')
    except (OSError, ValueError, yaml.YAMLError) as error:
        print(f'ERROR: {error}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
